#!/usr/bin/env bash
# set -e
if [ "$1" = "-v" ]; then
  exec 3>&1
else
  exec 3>/dev/null
fi

banner()  { echo "-----> $*" ; }
info()    { echo "       $*" ; }
warn()    { echo ">>>>>> $*" >&2 ; }

banner "Running bundler"
export PATH=".bin:$PATH"
rm -rf .bundle
if [ $CI ]; then
  bundle install --binstubs .bin --path vendor/bundle --without local development staging production "$@"
else
  bundle install --binstubs .bin --path vendor/bundle "$@"
fi

info "Done!"
